---

  - name: show values of dictionary for next include
    debug: var=val_from_dict

  - include: conversion.yml
    vars:
      val: "{{ 1 * (outer.val | int) }}"
    with_items: "{{ val_from_dict }}"
    loop_control:
      loop_var: outer
