---

  # include with value defined as constant
  - include: conversion.yml
    vars:
      val: 1
    tags:
      - constant

  - block:
    # include with value defined as fact
    - name: set test value -> 4
      set_fact:
        intval: 4
    - name: show value of fact for next include
      debug: var=intval
    - include: conversion.yml
      vars:
        val: "{{ intval }}"
    tags:
      - fact

  - block:
    # include with value defined in defaults/main.yml
    - name: show value from defaults/main.yml for next include
      debug: var=simple_val
    - include: conversion.yml
      vars:
        val: "{{ simple_val }}"
    tags:
      - simple

  # include with value defined in defaults/main.yml
  - include: dict.yml
    tags:
      - dict
